// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOslFc9fMds4Ou4gGq1WwZ8GyFN5XWc5s',
    appId: '1:590200128665:web:e18b4ba4abd40be3ef6408',
    messagingSenderId: '590200128665',
    projectId: 'dormtrack-3fbd6',
    authDomain: 'dormtrack-3fbd6.firebaseapp.com',
    databaseURL: 'https://dormtrack-3fbd6-default-rtdb.firebaseio.com',
    storageBucket: 'dormtrack-3fbd6.firebasestorage.app',
    measurementId: 'G-8T49NJX8BH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8x--gTKUErIYKUZSHj1yaBGup8dzXbsM',
    appId: '1:590200128665:android:3bbc435dd6ce8406ef6408',
    messagingSenderId: '590200128665',
    projectId: 'dormtrack-3fbd6',
    databaseURL: 'https://dormtrack-3fbd6-default-rtdb.firebaseio.com',
    storageBucket: 'dormtrack-3fbd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxKRrZncK6Kdx2ra5VsB7NU7BZbQhb0tc',
    appId: '1:590200128665:ios:a4d643946d7112bdef6408',
    messagingSenderId: '590200128665',
    projectId: 'dormtrack-3fbd6',
    databaseURL: 'https://dormtrack-3fbd6-default-rtdb.firebaseio.com',
    storageBucket: 'dormtrack-3fbd6.firebasestorage.app',
    iosBundleId: 'com.example.dormtrack',
  );
}
